config:
  use_colors: true
  send_anonymous_usage_stats: false
default:
  outputs:
    default:
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      schema: transforms
      threads: 4
      type: postgres